apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-spc
  namespace: {{ .Release.namespace }}
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.awsSecretName }}
        objectType: "secretsmanager"
        jmesPath:
          {{- range $secret := .Values.secrets }}
          - path: {{ $secret.name }}
            objectAlias: {{ $secret.name }}
          {{- end }}

  secretObjects:
    - secretName: {{ .Release.Name }}-secret
      type: Opaque
      data:
        {{- range $secret := .Values.secrets }}
        - objectName: {{ $secret.name }}
          key: {{ $secret.name | quote }}
        {{- end }}
