{{- if .Values.consumer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-consumer-deploy
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-consumer
    tenant: {{ .Values.tenant }}
    env: {{ .Values.environment }}
spec:
  replicas: {{ .Values.consumer.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-consumer
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-consumer
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
          {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccount.name }} # should be in the same namespace as the deployment
      volumes:
        - name: spc-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Release.Name }}-spc
      {{- if .Values.initContainers }}
      initContainers:
        {{- range $initContainer := .Values.initContainers }}
        - name: {{ $initContainer.name }}
          image: {{ $initContainer.image }}
          imagePullPolicy: {{ $initContainer.imagePullPolicy }}
          args: {{ $initContainer.args }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Release.Name }}-consumer
          image: {{ .Values.image }}
          command:
            {{- range .Values.consumer.command }}
            - {{ . }}
            {{- end }}
          args: {{ .Values.consumer.args }}
          resources:
            requests:
              memory: {{ .Values.consumer.resources.requests.memory }}
              cpu: {{ .Values.consumer.resources.requests.cpu }}
          volumeMounts:
            - name: spc-volume
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
            {{- range $secret := .Values.secrets.envs }}
            - name: {{ $secret.name }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-secret
                  key: {{ $secret.name }}
            {{- end }}
{{ end }}