{{- if .Values.dbMigrationJob.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrate-job
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-migrate-job
    tenant: prosperi
    env: {{ .Values.environment }}
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      name: {{ .Release.Name }}-migrate-job
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }} # should be in the same namespace as the deployment
      restartPolicy: Never
      volumes:
        - name: spc-volume
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: {{ .Release.Name }}-spc
      containers:
        - name: {{ .Release.Name }}-migrate-job
          image: {{ .Values.image }}
          command: [ "/bin/sh", "-c" ]
          args: {{ .Values.dbMigrationJob.args }}
          volumeMounts:
            - name: spc-volume
              mountPath: "/mnt/secrets-store"
              readOnly: true
          env:
            {{- range $secret := .Values.secrets.envs }}
            - name: {{ $secret.name | upper }}
              valueFrom:
                secretKeyRef:
                  name: {{ $.Release.Name }}-secret
                  key: {{ $secret.name }}
            {{- end }}
{{- end }}