{{- $serviceAccount := lookup "v1" "ServiceAccount" .Release.Namespace .Values.serviceAccount.name }}
{{- if not $serviceAccount }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.roleArn }}
automountServiceAccountToken: true
{{- end }}
